# Generated by Django 3.1.3 on 2020-11-17 16:34

from django.db import migrations, models
import dreams_item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=dreams_item.models.upload_image_path)),
                ('favorite', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('categories', models.CharField(max_length=100)),
            ],
        ),
    ]
