# Generated by Django 3.1.3 on 2020-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_item_category', '0002_auto_20201117_2024'),
        ('dreams_item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, to='dreams_item_category.Category'),
        ),
    ]
