# Generated by Django 3.1.3 on 2020-11-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_item', '0002_auto_20201117_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
