# Generated by Django 3.1.3 on 2020-11-29 18:09

from django.db import migrations, models
import django.db.models.deletion
import dreams_item.models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_item', '0003_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=dreams_item.models.upload_gallery_image_path)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams_item.item')),
            ],
        ),
    ]
