# Generated by Django 3.1.3 on 2020-12-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_item', '0004_itemgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
