# Generated by Django 3.1.3 on 2020-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
