# Generated by Django 3.1.3 on 2020-11-27 12:10

from django.db import migrations, models
import dreams_setting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to=dreams_setting.models.upload_image_path)),
                ('copyright', models.CharField(max_length=200)),
                ('about_us', models.CharField(max_length=300)),
            ],
        ),
    ]
